apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lo6vokt2o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lo6vokt2o-go 
  name: lo6vokt2o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lo6vokt2o-go 
